### ISSUE TITLE
FC on Startup

### ISSUE THREAD

**Issue by hidetag** [afollestad/better-picker-android#2]
**Device info**
Android version: 5.1.1
Device Manufacturer: Xiaomi
Device Name: Hongmi 2A

**Logcat**
```
05-07 10:05:12.062 11559-11559/com.afollestad.betterpickersample E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.afollestad.betterpickersample, PID: 11559
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.afollestad.betterpickersample/com.afollestad.betterpickersample.MainActivity}: java.lang.IndexOutOfBoundsException: Invalid index 0, size is 0
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2342)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2404)
        at android.app.ActivityThread.access$900(ActivityThread.java:154)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1315)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:135)
        at android.app.ActivityThread.main(ActivityThread.java:5296)
        at java.lang.reflect.Method.invoke(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:372)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:912)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:707)
        at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:107)
     Caused by: java.lang.IndexOutOfBoundsException: Invalid index 0, size is 0
        at java.util.ArrayList.throwIndexOutOfBoundsException(ArrayList.java:255)
        at java.util.ArrayList.get(ArrayList.java:308)
        at com.afollestad.betterpicker.base.BasePicker.getSelectedValueInColumn(BasePicker.kt:181)
        at com.afollestad.betterpicker.TimePicker.getTime(TimePicker.kt:82)
        at com.afollestad.betterpickersample.MainActivity.onCreate(MainActivity.kt:38)
        at android.app.Activity.performCreate(Activity.java:6093)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1106)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2295)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2404) 
        at android.app.ActivityThread.access$900(ActivityThread.java:154) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1315) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:135) 
        at android.app.ActivityThread.main(ActivityThread.java:5296) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at java.lang.reflect.Method.invoke(Method.java:372) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:912) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:707) 
```

**Reproduction Steps**
FC on startup

**Comment by afollestad** [comment]
Haven't had this issue. 

Might be related to the fact you're using Xposed.

**Comment by afollestad** [comment]
Oh it was debug code that was pushed up to the sample by accident, it doesn't affect the library itself though.
